name: test

on:
  push:
    branches:
      - main
    paths:
      - "condition"
      - ".github/workflows/test.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "condition"
      - ".github/workflows/test.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  test:
    name: Dummy test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run test on PR
      id: run-test-pr
      run: |
          echo  $(ls ${GITHUB_WORKSPACE})
          CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
          if [ "$CONDITION" == "fail" ]; then
            echo "PR Condition is 'fail'. Failing the step."
            exit 1
          else
            echo "PR Condition is not 'fail'. Continuing with the step."
          fi
      if: github.event_name == 'pull_request'

    - name: Check PR branch commit status
      id: test-commit-status-check
      run: |
        echo "${{ github.event.before }}"
        PR_BRANCH_COMMIT_STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.before }}/status" | jq -r '.state')
        echo "::set-output name=pr_commit_status::$PR_BRANCH_COMMIT_STATUS"
        echo "PR_COMMIT_STATUS=$PR_BRANCH_COMMIT_STATUS" >> "$GITHUB_OUTPUT"
      if: github.event_name == 'push'

    - name: Run test on deploy
      id: run-test-deploy
      run: |
          echo  $(ls ${GITHUB_WORKSPACE})
          CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
          if [ "$CONDITION" == "fail" ]; then
            echo "DEPLOY Condition is 'fail'. Failing the step."
            exit 1
          else
            echo "DEPLOY Condition is not 'fail'. Continuing with the step."
          fi
      if: github.event_name == 'push' && steps.test-commit-status-check.PR_COMMIT_STATUS == 'failure'

  deploy:
    needs: test
    name: Dummy deploy
    runs-on: ubuntu-latest

    steps:
    - name: Run deploy
      id: run-deploy
      run: echo "running deploy"
      if: github.event_name == 'push'
