name: test

on:
  push:
    branches:
      - main
    paths:
      - "condition"
      - ".github/workflows/test.yaml"

  pull_request:
    branches:
      - main
    paths:
      - "condition"
      - ".github/workflows/test.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true


jobs:
  test:
    name: Dummy test
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run test on PR
      id: run-test-pr
      run: |
          echo  $(ls ${GITHUB_WORKSPACE})
          CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
          if [ "$CONDITION" == "success" ]; then
            echo "PR Condition is 'success'. Continuing with the step."
          else
            echo "PR Condition is not 'success'. Failing the step."
            exit 1
          fi
      if: github.event_name == 'pull_request'

    - name: Check PR branch commit status
      id: test-commit-status-check
      run: |
          # Extract the pull request number from the GitHub event payload
          PULLS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/pulls")
          PR_NUMBER=$(echo "$PULLS" | jq -r '.[-1].number')
          echo "PR_NUMBER $PR_NUMBER"

          # Fetch the commits in the pull request
          COMMITS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/pulls/${PR_NUMBER}/commits")
          echo "LAST COMMITS $COMMITS"

          # Extract the SHA of the last commit in the pull request
          LAST_COMMIT=$(echo "$COMMITS" | jq -r '.[-1].sha')
          echo "LAST COMMIT $LAST_COMMIT"

          # Look for failures in the checks of the commits
          CHECK_RUNS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/commits/$LAST_COMMIT/check-runs")
          LAST_PR_COMMIT_CHECKS_STATUS=$(echo "$CHECK_RUNS" | jq -r '[ .check_runs[] | select(.conclusion == "failure") | .conclusion] | first // "success"')

          echo "STATUS=$LAST_PR_COMMIT_CHECKS_STATUS" >> "$GITHUB_OUTPUT"
          echo "LAST_PR_COMMIT_CHECKS_STATUS $LAST_PR_COMMIT_CHECKS_STATUS"

      if: github.event_name == 'push'


    - name: Run test on deploy
      id: run-test-deploy
      run: |
          echo  $(ls ${GITHUB_WORKSPACE})
          CONDITION=$(cat ${GITHUB_WORKSPACE}/condition)
          if [ "$CONDITION" == "success" ]; then
            echo "PR Condition is 'success'. Continuing with the step."
          else
            echo "PR Condition is not 'success'. Failing the step."
            exit 1
          fi
      if: github.event_name == 'push' && steps.test-commit-status-check.STATUS == 'failure'

  deploy:
    needs: test
    name: Dummy deploy
    runs-on: ubuntu-latest

    steps:
    - name: Run deploy
      id: run-deploy
      run: echo "running deploy"
      if: github.event_name == 'push'
